function Hd = 200least_sqr
%200LEAST_SQR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 30-Dec-2023 12:38:18

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 7680000;  % Sampling Frequency

N     = 200;     % Order
Fpass = 180000;  % Passband Frequency
Fstop = 200000;  % Stopband Frequency
Wpass = 1;       % Passband Weight
Wstop = 0.1;     % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
